version: "3.8"
services:
  gateway:
    build:
      context: gateway/docker/development/nginx
    ports:
      - "${PORT}:${PORT}"
      - "${BACK_PORT}:${BACK_PORT}"
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: frontend/docker/development/nginx
    volumes:
      - ./frontend:/app
      - ./frontend/docker/development/nginx/conf.d:/etc/nginx/conf.d

  api:
    build:
      context: api/docker/development/nginx
    volumes:
      - ./api:/app
      - ./api/docker/development/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: api/docker/development/php-fpm
    volumes:
      - ./api:/app
